urlwithoutschema: jdbc:mysql://localhost:3306/
urlparameters: ?verifyServerCertificate=false&useSSL=true

server:
  context-path: /api
  port: 8080

logging:
  file: twitterapi.log

spring:
  application:
    name: twitter-secretary
  social:
    twitter:
      app-id: yix4Ai9xDbWBKV3yFPFGs8Nkf
      app-secret: 9rXtdeYe5v3wmGR5E96ubiXRDeWzZFgRt2ZYdgSKeQFivw0OtD
  datasource:
    url: ${urlwithoutschema}${spring.datasource.schema}${urlparameters}
    username: root
    password: pa55word
    schema: twitter_secretary
    initialize: false
    encoding:
      params: ?useUnicode=yes&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        default_schema: ${spring.datasource.schema}
  jackson:
    serialization:
      write-dates-as-timestamps: false

flyway:
  url: ${spring.datasource.url}
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  schemas: ${spring.datasource.schema}
  locations: classpath:db/migration
  out-of-order: true
